Debug = false

[Server]
BindIP = "127.0.0.1" # Make it 0.0.0.0 if you want to expose it to the world
                     # without using an HTTPS terminating proxy in front
Port = 8080

[Redis]
Connection = "redis-1337.c10.us-east-1-1.ec2.cloud.redislabs.com:1337"
Username = "default"
Password = "passwordOfTheRedisUser"
Cluster = false
Failover = false
# MasterName = ""  # Only required when Failover = true
# Connections = [] # Only required when Cluster = true or Failover = true
Concurrency = 1

[[Users]]
Key = "YourPushoverUserKeyHere"

  # The URL for this application would be:
  # http://your.server/1/messages.json
  [[Users.Applications]]
  Token = "YourPushoverApplicationTokenHere"
  Name = "Zsh"
  IconPath = "/some/icon.png"
  Target = "your_target_xmpp"
  Format = "pushover"

  # The URL for this application would be:
  # http://your.server/SomeRandomUniqueTokenHere
  [[Users.Applications]]
  Token = "SomeRandomUniqueTokenHere"
  Name = "Grafana"
  IconPath = "/some/icon.png"
  Target = "your_target_matrix"
  Format = "custom"
  CustomFormat.Message = '{{ webhook "body.message" }}'
  CustomFormat.Title = '{{ webhook "body.title" }}'
  CustomFormat.URL = '{{ webhook "body.externalURL" }}'

[[Targets]]
ID = "your_target_xmpp"
Type = "xmpp"

  [Targets.Args]
  server = "conversations.im"
  tls = "false"
  username = "your_overpush_account@conversations.im"
  password = "YourOverpushAccountPassword"
  destination = "you@your-xmpp-server.im"

[[Targets]]
ID = "your_target_matrix"
Type = "apprise"

  [Targets.Args]
  apprise = "/usr/bin/apprise"
  connection = "matrixs://my_bot:hunter2@matrix.org:443/!xXxXxXxXXXxxxXXXxX:matrix.org?format=markdown"

